### PR TITLE
Update to 7.10.2

### PR DESCRIPTION
**Pull request by Christophvh**
I updated my cloud instance to 7.10.2 and now the indexing is broken since this version is still on 7.10.1

### CODE REVIEW

**Comment by Christophvh** [comment]
I have signed the agreement. Is there a way to redo the CLA check?

**Comment by JasonStoltz** [comment]
Hey @Christophvh, that shouldn't break your cloud instance. Can you elaborate on the problem you're having?

**Comment by Christophvh** [comment]
@JasonStoltz After upgrading to 7.10.2 in elastic cloud i got following error when trying to index:

The only thing that changed is the upgrade. And the error also refers to lib/client.js
```
 ERROR  [                                                                                                                                                               18:51:11
  'Internal server error. Please check your application server logs for more details and contact Elastic support if the problem persists'
]

 ERROR  Internal Server Error                                                                                                                                           18:51:11

  at Request._callback (/node_modules/@elastic/app-search-node/lib/client.js:95:26)
```

**Comment by Christophvh** [comment]
We have found the issue. Not related to version after all. Sorry for the confusion

**Pull request closed without merging**
