### PR TITLE
Add ability to pass sign options to, fixes #46

### LINKED ISSUE #46: Allow configuring JWT signature options for signed keys
Currently, the options are hard coded as `{ algorithm: SIGNED_SEARCH_TOKEN_JWT_ALGORITHM }`. So if you wanted to pass in an option such as `expiresIn`, you can not.

PR incoming

### PR DESCRIPTION
**Pull request by ckeboss**
Fixes #46

### CODE REVIEW

**Comment by ckeboss** [comment]
@JasonStoltz Any thoughts?

**Comment by JasonStoltz** [comment]
Hey @ckeboss. 

Generally, I'm avoiding updates to this library, as we are actively working on a new client to replace this one.

Is this something that will unblock you on a task? If so, this looks like a small, targeted change which I'd be good with merging. Give me a little time today to look at the code a bit closer and consider it.

**Comment by ckeboss** [comment]
It is not a huge deal, we are just using a fork right now. Can you elaborate on plans for a new client?

**Comment by JasonStoltz** [comment]
@ckeboss We're moving towards clients for all of Enterprise Search, not specifically App Search. They are based off of the very mature elasticsearch clients, as well as maintained by the dedicated clients team. All-in-all, they are much better clients. Here's the example of the python client: https://github.com/elastic/enterprise-search-python.

**Comment by ckeboss** [comment]
Gotcha. Looks to be be partially generated from an OpenAPI spec? Any reason the spec is not available?

I assume the wait is updating the JS templates / parsing? I know openapi-generator / swagger-codegen do not have very mature javascript support.

**Comment by JasonStoltz** [comment]
I don't think there is a specific reason that the OpenAPI spec is not available yet, I just don't think we've published it anywhere.

And yes, there's quite a bit of work that goes into these clients, even if they are generated. @delvedor will be working on the node client; he's already done some amazing things with the [elasticsearch client](https://github.com/elastic/elasticsearch-js).

**Review by JasonStoltz — APPROVED** [review]

**Comment by JasonStoltz** [comment]
@ckeboss I published https://github.com/elastic/app-search-node/releases/tag/v7.13.1, give it a try and let me know if everything looks good.

**Comment by ckeboss** [comment]
@JasonStoltz Thank you, we have migrated to it and everything it working well.

**Pull request merged**
